npm cache clean
npm install -y forever
npm install -y express
npm install -y body-parser
npm install -y morgan
npm install -y express-session
npm install -y method-override
npm install -y serve-favicon
npm install -y express-error-handler
npm install -y connect-multiparty
npm install -y async
npm install -y mysql
npm install -y crypto
npm install -y iconv
npm install -y log4js
npm install -y mkdirp
npm install -y moment
npm install -y querystring
npm install -y date-utils
npm install -y cluster
npm install -y nodemailer
npm install -y nodemailer-smtp-transport
npm install -y mongodb
npm install -y emailjs
npm install -y jsftp
npm install -y connect-mongo
npm install -y mongoose
npm install -y cookie-parser
npm install -y generic-pool
npm install -y iab_verifier
npm install -y xml2js
npm install -y request
npm install -y ssh2
npm install -y lwip